### ISSUE TITLE
Core-concept 

### ISSUE THREAD

**Issue by Pavankumar07s** [Pavankumar07s/udemy-react#3]
<h2>give the glass morphism effect to core concept div.</h2>

![Screenshot from 2024-05-19 14-44-20](https://github.com/Pavankumar07s/udemy-react/assets/136047863/3929c19e-a5f7-43fd-b2a3-a40d68c2f743)

**Comment by aayushyatiwari** [comment]
assign me the issue.

**Comment by Pavankumar07s** [comment]
issue solved.
