### ISSUE TITLE
Glass effect 

### ISSUE THREAD

**Issue by Pavankumar07s** [Pavankumar07s/udemy-react#9]
<h1>Add **glass effect** on the **tab**-**content** **container</h1>**
![Screenshot from 2024-05-19 18-43-24](https://github.com/Pavankumar07s/udemy-react/assets/136047863/ae826969-e1da-470a-a96d-56f1ea886d1b)

**Comment by Seba-Aguero** [comment]
Hi! Could you assign me this issue please? I would like to work on it.

**Comment by Pavankumar07s** [comment]
Hi Seba-Aguero

I've assigned this issue to you  Please let me know if you have any questions or need any assistance.

Thanks,
Pavan kumar

**Comment by Pavankumar07s** [comment]
Hi  @Seba-Aguero ,

Thank you for your contribution! I appreciate the effort you put into addressing the issue. Here are some thoughts and suggestions on your changes:

Overall, this is a solid contribution, and with a few tweaks, it will be ready to merge. Looking forward to your updates!

Best regards,
Pavan kumar
